### ISSUE TITLE
Lighter docker setup

### ISSUE THREAD

**Issue by davidzwa** [kalemena/docker-zeroconf#1]
Thanks for sharing! Your docker setup is not as fast as it could be, so I though to share a simple setup which works for me:

<pre>
FROM python:3
ADD [ "examples", "/examples" ]    
RUN pip install zeroconf

WORKDIR /examples

CMD ["bash"]
</pre>

This is much easier to understand for developers, because all we need to know is: does it have python and are my packages installed 👍

**Comment by kalemena** [comment]
Thanks for sharing too, davidzwa.
While writing this Dockerfile example, I had my own use case in mind where base image must be CentOS because zeroconf is not the only installed brick.
But you're right here!

**Comment by davidzwa** [comment]
Btw, did you have Zeroconf outside the docker network working? I can't discover any device which is running on my LAN. I've seen stuff like multicast being not supported by docker.

Quite a hard question, I believe, but had to try.
So far I've hit a wall: https://github.com/docker/libnetwork/issues/552

**Comment by kalemena** [comment]
Unfortunately, I cannot respond to that one :-/

I just changed Dockerfile with your proposal. 

Just a note: python:3 base image is 930MB, while CentOS is 200MB.
I am not looking after size reduction, but some people may be.

**Comment by davidzwa** [comment]
slim-buster or alpine should do the trick! :)
https://pythonspeed.com/articles/base-image-python-docker-images/

Thx for the adjustment
